from pathlib import Path
p=Path('/mnt/data/v30work/app.py')
s=p.read_text()
old='''@app.route("/attendance")\n@login_required\ndef attendance():\n    if not can_view_attendance_page():\n        flash("只有正式队员可以查看出勤率统计。", "error")\n        return redirect(url_for("dashboard"))\n    try:\n        sync_attendance_events()\n    except Exception:\n        db.session.rollback()\n    regular_only = request.args.get("regular") == "1"\n    users_query = User.query.filter_by(disabled=False)\n    if regular_only:\n        users_query = users_query.filter(User.is_regular_member.is_(True))\n    users_list = users_query.order_by(User.is_regular_member.desc(), User.callsign.asc()).all()\n    events = AttendanceEvent.query.order_by(AttendanceEvent.event_date.desc(), AttendanceEvent.id.desc()).all()\n    records = AttendanceRecord.query.filter(AttendanceRecord.present.is_(True)).all()\n    present_map = {(r.user_id, r.event_id): True for r in records}\n    return render_template(\n        "attendance.html",\n        users=users_list,\n        events=events,\n        present_map=present_map,\n        regular_only=regular_only,\n    )\n'''
new='''@app.route("/attendance")\n@login_required\ndef attendance():\n    if not can_view_attendance_page():\n        flash("只有正式队员可以查看出勤率统计。", "error")\n        return redirect(url_for("dashboard"))\n    try:\n        sync_attendance_events()\n    except Exception:\n        db.session.rollback()\n    regular_only = request.args.get("regular") == "1"\n    selected_year_raw = request.args.get("year", "").strip()\n    selected_year = int(selected_year_raw) if selected_year_raw.isdigit() else None\n\n    users_query = User.query.filter_by(disabled=False)\n    if regular_only:\n        users_query = users_query.filter(User.is_regular_member.is_(True))\n    users_list = users_query.order_by(User.is_regular_member.desc(), User.callsign.asc()).all()\n\n    all_events_for_years = AttendanceEvent.query.order_by(AttendanceEvent.event_date.desc(), AttendanceEvent.id.desc()).all()\n    available_years = sorted({e.event_date.year for e in all_events_for_years}, reverse=True)\n\n    events_query = AttendanceEvent.query\n    if selected_year:\n        year_start = datetime(selected_year, 1, 1).date()\n        year_end = datetime(selected_year + 1, 1, 1).date()\n        events_query = events_query.filter(AttendanceEvent.event_date >= year_start, AttendanceEvent.event_date < year_end)\n    events = events_query.order_by(AttendanceEvent.event_date.desc(), AttendanceEvent.id.desc()).all()\n    event_ids = [e.id for e in events]\n\n    records_query = AttendanceRecord.query.filter(AttendanceRecord.present.is_(True))\n    if event_ids:\n        records_query = records_query.filter(AttendanceRecord.event_id.in_(event_ids))\n    else:\n        records_query = records_query.filter(False)\n    records = records_query.all()\n    present_map = {(r.user_id, r.event_id): True for r in records}\n    attendance_counts = {}\n    for r in records:\n        attendance_counts[r.user_id] = attendance_counts.get(r.user_id, 0) + 1\n\n    regular_members = User.query.filter_by(disabled=False, is_regular_member=True).order_by(User.callsign.asc()).all()\n    return render_template(\n        "attendance.html",\n        users=users_list,\n        events=events,\n        present_map=present_map,\n        regular_only=regular_only,\n        selected_year=selected_year,\n        available_years=available_years,\n        attendance_counts=attendance_counts,\n        regular_members=regular_members,\n    )\n'''
if old not in s:
    raise SystemExit('attendance function block not found')
s=s.replace(old,new)
old='''        organizer = request.form.get("organizer", "").strip()\n        if not name:\n            raise ValueError("活动名称不能为空。")\n        event = AttendanceEvent(\n            name=name, event_date=event_date, location=location, organizer=organizer,\n            is_manual=True, created_by_id=current_user.id\n        )\n'''
new='''        organizer = request.form.get("organizer", "").strip()\n        if not name:\n            raise ValueError("活动名称不能为空。")\n        event = AttendanceEvent(\n            name=name, event_date=event_date, location=location, organizer=organizer,\n            is_manual=True, created_by_id=current_user.id\n        )\n'''
# no change, keep for context
insert_after='''    return redirect(url_for("attendance"))\n\n\n@app.route("/attendance/<int:event_id>/<int:user_id>/toggle", methods=["POST"])\n'''
insert='''    return redirect(url_for("attendance"))\n\n\n@app.route("/attendance/events/<int:event_id>/edit", methods=["POST"])\n@login_required\n@attendance_manage_required\ndef edit_attendance_event(event_id):\n    event = db.session.get(AttendanceEvent, event_id)\n    if not event:\n        flash("历史活动不存在。", "error")\n        return redirect(url_for("attendance"))\n    if not event.is_manual:\n        flash("平台自动生成的出勤活动不能在这里编辑。", "error")\n        return redirect(url_for("attendance"))\n    try:\n        name = request.form.get("name", "").strip()\n        event_date = datetime.strptime(request.form.get("event_date", ""), "%Y-%m-%d").date()\n        location = request.form.get("location", "").strip()\n        organizer = request.form.get("organizer", "").strip()\n        if not name:\n            raise ValueError("活动名称不能为空。")\n        event.name = name\n        event.event_date = event_date\n        event.location = location\n        event.organizer = organizer\n        db.session.commit()\n        flash("历史活动已更新。", "success")\n    except Exception as exc:\n        db.session.rollback()\n        flash(str(exc), "error")\n    return redirect(request.referrer or url_for("attendance"))\n\n\n@app.route("/attendance/events/<int:event_id>/delete", methods=["POST"])\n@login_required\n@attendance_manage_required\ndef delete_attendance_event(event_id):\n    event = db.session.get(AttendanceEvent, event_id)\n    if not event:\n        flash("历史活动不存在。", "error")\n        return redirect(url_for("attendance"))\n    if not event.is_manual:\n        flash("平台自动生成的出勤活动不能在这里删除。", "error")\n        return redirect(url_for("attendance"))\n    db.session.delete(event)\n    db.session.commit()\n    flash("历史活动已删除。", "success")\n    return redirect(request.referrer or url_for("attendance"))\n\n\n@app.route("/attendance/<int:event_id>/<int:user_id>/toggle", methods=["POST"])\n'''
if insert_after not in s:
    raise SystemExit('insert point not found')
s=s.replace(insert_after, insert)
p.write_text(s)
