<template>
  <section class="training-admin">
    <header class="training-header"><div><span>LASER DRY FIRE</span><h1>训练屋管理</h1></div><el-button @click="load">刷新</el-button></header>
    <div class="training-metrics"><article><b>{{ overview.open_rooms || 0 }}</b><span>开放房间</span></article><article><b>{{ overview.running_sessions || 0 }}</b><span>训练中</span></article><article><b>{{ overview.online_devices || 0 }}</b><span>在线靶机</span></article><article><b>{{ overview.today_completed || 0 }}</b><span>今日完成</span></article></div>
    <el-tabs v-model="tab" @tab-change="load">
      <el-tab-pane label="房间" name="rooms"><el-table :data="rooms" border><el-table-column prop="room_code" label="房间号" width="130"/><el-table-column prop="name" label="名称"/><el-table-column label="房主"><template #default="{row}">{{ row.owner_callsign || row.owner_username }}</template></el-table-column><el-table-column label="成员"><template #default="{row}">{{ row.member_count }}/10</template></el-table-column><el-table-column label="靶机"><template #default="{row}">{{ row.target_count }} 台</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="130"><template #default="{row}"><el-button v-if="row.status === 'open'" type="danger" size="small" @click="closeRoom(row)">强制关闭</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="靶机设备" name="devices"><div class="training-actions"><el-button type="primary" @click="deviceForm={ name: '', device_code: '', target_name: '', status: 'offline', calibration_status: 'pending' }">新增设备</el-button></div><el-table :data="devices" border><el-table-column prop="device_code" label="设备编号"/><el-table-column prop="name" label="名称"/><el-table-column prop="target_name" label="靶纸" width="150"/><el-table-column prop="room_name" label="房间"/><el-table-column prop="target_no" label="靶机号" width="90"/><el-table-column prop="status" label="连接"/><el-table-column prop="calibration_status" label="校准"/><el-table-column prop="frame_rate" label="FPS" width="90"/><el-table-column prop="last_heartbeat_at" label="最后心跳"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button size="small" @click="deviceForm={...row}">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="训练成绩" name="sessions"><el-table :data="sessions" border><el-table-column prop="session_code" label="轮次" width="190"/><el-table-column label="队员"><template #default="{row}">{{row.callsign || row.username}}</template></el-table-column><el-table-column prop="room_name" label="房间"/><el-table-column prop="training_mode" label="模式"/><el-table-column prop="target_count" label="靶机" width="70"/><el-table-column prop="total_hits" label="命中" width="70"/><el-table-column prop="average_accuracy" label="精准度" width="100"/><el-table-column prop="duration_ms" label="用时(ms)" width="120"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button size="small" @click="sessionForm={...row, reason:''}">修改</el-button><el-button size="small" type="danger" @click="deleteSession(row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="审计记录" name="audits"><el-table :data="audits" border><el-table-column prop="created_at" label="时间" width="180"/><el-table-column label="操作人"><template #default="{row}">{{row.callsign || row.username || '-'}}</template></el-table-column><el-table-column prop="entity_type" label="对象"/><el-table-column prop="entity_id" label="ID"/><el-table-column prop="action" label="操作"/><el-table-column prop="reason" label="原因" min-width="180"/></el-table></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="deviceForm" title="靶机设备" width="440"><el-form v-if="deviceForm" label-position="top"><el-form-item label="设备编号"><el-input v-model="deviceForm.device_code" :disabled="!!deviceForm.id"/></el-form-item><el-form-item label="名称"><el-input v-model="deviceForm.name"/></el-form-item><el-form-item label="靶纸名称"><el-input v-model="deviceForm.target_name"/></el-form-item><el-form-item label="连接状态"><el-select v-model="deviceForm.status"><el-option label="离线" value="offline"/><el-option label="在线" value="online"/><el-option label="停用" value="disabled"/></el-select></el-form-item><el-form-item label="校准状态"><el-select v-model="deviceForm.calibration_status"><el-option label="待校准" value="pending"/><el-option label="就绪" value="ready"/><el-option label="失败" value="failed"/></el-select></el-form-item><el-form-item label="帧率"><el-input-number v-model="deviceForm.frame_rate" :min="1" :max="240"/></el-form-item></el-form><template #footer><el-button @click="deviceForm=null">取消</el-button><el-button type="primary" @click="saveDevice">保存</el-button></template></el-dialog>
    <el-dialog v-model="sessionForm" title="更正训练成绩" width="440"><el-form v-if="sessionForm" label-position="top"><el-form-item label="命中数"><el-input-number v-model="sessionForm.total_hits" :min="0"/></el-form-item><el-form-item label="平均精准度"><el-input-number v-model="sessionForm.average_accuracy" :min="0" :max="100" :precision="2"/></el-form-item><el-form-item label="用时（毫秒）"><el-input-number v-model="sessionForm.duration_ms" :min="0"/></el-form-item><el-form-item label="修改原因"><el-input v-model="sessionForm.reason"/></el-form-item></el-form><template #footer><el-button @click="sessionForm=null">取消</el-button><el-button type="primary" @click="saveSession">保存</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import { ref, onMounted } from 'vue'
import { ElMessageBox } from 'element-plus'
import { api } from '../api'
const tab = ref('rooms'), overview = ref({}), rooms = ref([]), devices = ref([]), sessions = ref([]), audits = ref([]), deviceForm = ref(null), sessionForm = ref(null)
async function load() { overview.value = await api('/api/training/admin/overview'); const endpoint = { rooms: 'rooms', devices: 'devices', sessions: 'sessions', audits: 'audits' }[tab.value]; if (endpoint) ({ rooms, devices, sessions, audits }[endpoint].value = await api(`/api/training/admin/${endpoint}`)) }
async function closeRoom(room) { const { value: reason } = await ElMessageBox.prompt('请填写强制关闭原因', '关闭房间', { inputPattern: /.+/, inputErrorMessage: '必须填写原因' }); await api(`/api/training/admin/rooms/${room.id}/close`, { method: 'PUT', body: { reason } }); await load() }
async function saveDevice() { const item = deviceForm.value; const url = item.id ? `/api/training/admin/devices/${item.id}` : '/api/training/admin/devices'; await api(url, { method: item.id ? 'PUT' : 'POST', body: item }); deviceForm.value = null; await load() }
async function saveSession() { const item = sessionForm.value; if (!item.reason) return; await api(`/api/training/admin/sessions/${item.id}`, { method: 'PUT', body: item }); sessionForm.value = null; await load() }
async function deleteSession(item) { const { value: reason } = await ElMessageBox.prompt('请填写删除原因', '删除成绩', { inputPattern: /.+/, inputErrorMessage: '必须填写原因' }); await api(`/api/training/admin/sessions/${item.id}`, { method: 'DELETE', body: { reason } }); await load() }
onMounted(load)
</script>
<style scoped>
.training-header,.training-actions{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.training-header span{color:#7f9f33;font-size:12px}.training-header h1{margin:3px 0 0;font-size:23px}.training-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.training-metrics article{border:1px solid #e3e7df;padding:17px;background:#fff}.training-metrics b{display:block;font-size:28px;color:#31460d}.training-metrics span{font-size:12px;color:#73806b}@media(max-width:800px){.training-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
